version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &update-npm
    run:
      name: Update NPM version
      command: 'sudo npm install -g npm@latest'
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules

jobs:
  integration_tests_node_10:
    working_directory: ~/nest
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Integration tests for node v10
          command: npm run test:integration

  integration_tests_node_12:
    working_directory: ~/nest
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Integration tests for node v12
          command: npm run test:integration

  integration_tests_node_14:
    working_directory: ~/nest
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Integration tests for node v14
          command: npm run test:integration

  coverage:
    working_directory: ~/nest
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Test coverage
          command: npm run test:cov
      - coveralls/upload:
          path_to_lcov: ./coverage/e2e/lcov.info

workflows:
  version: 2
  test:
    jobs:
      - integration_tests_node_10
      - integration_tests_node_12
      - integration_tests_node_14
  coverage:
    jobs:
      - coverage
