version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm install --force --unsafe-perm
  - &update-npm
    run:
      name: Update NPM version
      command: 'sudo npm install -g npm@latest'
  - &run-lint
    run:
      name: Linting
      command: npm run lint
  - &run-integration
    run:
      name: Integration tests
      command: npm run test:integration
  - &save-cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &remove-latest-nestjs
    run:
      name: Remove latest nestjs
      command: npm remove @nestjs/common @nestjs/core @nestjs/platform-express @nestjs/testing rxjs

jobs:
  integration_tests_node_12:
    resource_class: small
    working_directory: ~/nest
    docker:
      - image: cimg/node:12.22.0
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - *run-lint
      - *run-integration

  integration_tests_node_14:
    resource_class: small
    working_directory: ~/nest
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - *run-lint
      - *run-integration

  integration_tests_node_16:
    resource_class: small
    working_directory: ~/nest
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - *run-lint
      - *run-integration

  ### Testing support for older versions of nestjs/rxjs
  integration_tests_nestjs_7_0_0:
    resource_class: small
    working_directory: ~/nest
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *remove-latest-nestjs
      - run:
          name: Install nestjs 7.0.0 and deps
          command: npm install -D @nestjs/common@^7.0.0 @nestjs/core@^7.0.0 @nestjs/platform-express@^7.0.0 @nestjs/testing@^7.0.0 rxjs@^6.0.0
      - *run-lint
      - *run-integration

  integration_tests_nestjs_6_0_0:
    resource_class: small
    working_directory: ~/nest
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *remove-latest-nestjs
      - run:
          name: Install nestjs 6.0.0 and deps
          command: npm install -D @nestjs/common@^6.0.0 @nestjs/core@^6.0.0 @nestjs/platform-express@^6.0.0 @nestjs/testing@^6.0.0 rxjs@^6.0.0
      - *run-lint
      - *run-integration

  coverage:
    working_directory: ~/nest
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - *update-npm
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Test coverage
          command: npm run test:cov
      - coveralls/upload:
          path_to_lcov: ./coverage/e2e/lcov.info

workflows:
  version: 2
  test:
    jobs:
      - integration_tests_node_12
      - integration_tests_node_14
      - integration_tests_node_16
      - integration_tests_nestjs_7_0_0
      - integration_tests_nestjs_6_0_0
  coverage:
    jobs:
      - coverage
